theme: jekyll-theme-minimal
title: "The Condemned Ship"
description: "A remake of a game that is more than twenty years old. This website contains the documentation of the project."
logo: "./assets/images/Logo/Logo.png"
show_downloads: true
google_analytics: "UA-132816390-1"